name: Terraform CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Init Terraform
        working-directory: terraform
        run: terraform init
      
      - name: Package Lambda
        run: zip -j lambda-notes.zip ../src/*.py

      - name: Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
