name: Terraform Checks

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
     
      - name: Terraform Format Check
        run: terraform fmt

      - name: Package Lambda
        run: zip -j lambda-notes.zip ../src/*.py

      - name: Terraform Validate
        run: terraform validate 

