name: Terraform Checks

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
     
      - name: Terraform Format Check
        run: terraform fmt

      - name: Package Lambda
        run: zip -j lambda-notes.zip ../src/*.py

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: terraform plan


